/*
Written by Vaishnavi Bhosale for CS6364.004, assignment 4, starting October 25, 2017.
    NetID: vbb160030
    Designed the database for a contact manager, now this is a scaled-back contact manager program.   
    A screen is created that lets you add, change, search and delete contacts.  
    The purpose of this assignment is to learn how to interface to a database from within a program.
 */

//Import required packages
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.InputVerifier;
public class ContactManager extends javax.swing.JFrame {

    /**
     * Creates new form ContactManager
     */
    public ContactManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name:");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText(" INFORMATION OF CONTACTED PERSON");

        jLabel3.setText("Last Name:");

        jTextField2.setText("jTextField2");

        jLabel4.setText("BirthDate:");

        jLabel5.setText("Sex:");

        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Email Id:");

        jLabel8.setText("Contact Number:");

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setText("jTextField7");

        jLabel9.setText("Address Line:");

        jLabel10.setText("State:");

        jTextField8.setText("jTextField8");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel11.setText("City:");

        jTextField9.setText("jTextField9");

        jLabel12.setText("ZIP CODE:");

        jTextField10.setText("jTextField10");

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("SSN:");

        jTextField4.setText("jTextField4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "First Name", "Last Name", "BirthDate", "SEX", "Phone", "Address", "Zip Code"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                                        .addComponent(jTextField2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5)
                                            .addGap(52, 52, 52)
                                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(794, 794, 794))))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(9, 9, 9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(2000, 1800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("First Name:");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 100, 230, 70);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 90, 520, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel2.setText(" INFORMATION OF CONTACTED PERSON");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 0, 1300, 82);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(880, 110, 210, 44);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1110, 90, 610, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("BirthDate:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 340, 240, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Sex:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(930, 270, 150, 70);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(71, 388, 0, 0);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1120, 430, 600, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Email Id:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(910, 440, 200, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Contact Number:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 480, 309, 44);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1050, 770, 590, 100);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(340, 610, 1140, 100);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Address Line:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 610, 280, 110);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("State:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 770, 140, 110);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(270, 930, 520, 80);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("City:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(950, 760, 130, 100);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField9.setToolTipText("");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(270, 770, 530, 100);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("ZIP CODE:");
        jLabel12.setMaximumSize(new java.awt.Dimension(222, 222));
        jLabel12.setMinimumSize(new java.awt.Dimension(222, 222));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 910, 210, 120);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField10.setToolTipText("Only 10 digits are allowed");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(390, 460, 440, 80);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 1060, 250, 80);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 1060, 250, 80);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 1060, 240, 80);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1150, 1060, 240, 80);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("SSN:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 230, 150, 50);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(300, 220, 520, 70);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.setVerifyInputWhenFocusTarget(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(490, 340, 160, 60);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(670, 340, 160, 60);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(320, 340, 150, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 10, 580, 70);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jRadioButton1.setText("  Male");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(1040, 280, 170, 50);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jRadioButton2.setText("   Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(1250, 280, 270, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton5.setText("RETRIEVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(890, 1060, 230, 80);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "FIEST NAME", "LAST NAME", "BIRTHDATE", "SEX", "ADDRESS", "STATE", "CITY", "ZIP", "EMAIL", "PHONE"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 1170, 1690, 402);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1430, 1060, 200, 80);

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

/**************************************************************************
 * INSERT all values entered by user into database by calling stored procedure.* 
 * In stored procedure, all queries to insert values into tables are written. 
 **************************************************************************/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // INSERT button when clicked then handling code here:
        //Get all values from the design interface
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        String mail =  jTextField5.getText();
        String address = jTextField7.getText();  
        String state = jTextField9.getText();
        String city = jTextField6.getText();  
        jLabel14.setText("");
        int ssn = Integer.parseInt(jTextField4.getText());
        int num = Integer.parseInt(jTextField10.getText());
        int zip = Integer.parseInt(jTextField8.getText());
        
        String sex=null;
        String date=null;
        int d=0,m=0,y=0;
        if(jRadioButton1.isSelected())
        {
            sex = "M";
        }
        else if(jRadioButton2.isSelected())
        {
            sex = "F";
        }
       
       //Get date values from ComboBox
        Object selectedItem = jComboBox3.getSelectedItem();
        if (selectedItem != null)
        {
             String mm = selectedItem.toString();
             m = Integer.parseInt(mm);
        }
        Object selectedItem2 = jComboBox1.getSelectedItem();
        if (selectedItem2 != null)
        {
             String dd = selectedItem2.toString();
             d = Integer.parseInt(dd);
        }
        Object selectedItem3 = jComboBox2.getSelectedItem();
        if (selectedItem3 != null)
        {
             String yy = selectedItem3.toString();
             y = Integer.parseInt(yy);
        }  
 
        //interface CallableStatement declared to execute SQL stored procedures
        CallableStatement cstmt2;
        CallableStatement stmt; 
        CallableStatement cstmt;
        CallableStatement cstmt3;
     
//Stored procedure is called and values are passed to it then INSERT INTO TABLE queries are excecuted in it.
    try {
        // Prepare a call to the stored procedure 'INSERT_PERSON' with five parameters
        String SQL = "{call INSERT_PERSON (?, ?, ?, ?, ?)}";
        cstmt = con.prepareCall (SQL);
        // Set a parameter by index
        cstmt.setString(2,fname);
        cstmt.setString(3,lname);
        cstmt.setInt(1,ssn);
        cstmt.setString(4,sex);
        date = y+"-"+m+"-"+d;
        cstmt.setString(5,date);
        cstmt.executeUpdate();
    }
    catch (SQLException e) {
        //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("PERSON NOT INSERTED");
    }
    
    try {
        // Prepare a call to the stored procedure 'INSERT_PHONE' with two parameters
        String SQL3 = "{call INSERT_PHONE (?, ?)}";
        stmt = con.prepareCall (SQL3);
        // Set a parameter by index
        stmt.setInt(1,num);
        stmt.setInt(2,ssn);
        stmt.executeUpdate();
    }
    catch (SQLException e) {
        //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("  PHONE NOT INSERTED");
    }
   
    try {
        // Prepare a call to the stored procedure 'INSERT_EMAIL' with two parameters
        String SQL4 = "{call INSERT_EMAIL (?, ?)}";
        cstmt2 = con.prepareCall (SQL4);
        // Set a parameter by index
        cstmt2.setString(1,mail);
        cstmt2.setInt(2,ssn);
        cstmt2.executeUpdate();
    }
    catch (SQLException e) {
        //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("MAIL NOT INSERTED");
    }
    
    try {
        // Prepare a call to the stored procedure 'INSERT_ADDRESS' with five parameters        
        String SQL5 = "{call INSERT_ADDRESS (?, ?, ?, ?, ?)}";
        cstmt3 = con.prepareCall (SQL5);
        // Set a parameter by index
        cstmt3.setInt(1,ssn);
        cstmt3.setString(2,city);
        cstmt3.setString(3,state);
        cstmt3.setInt(4,zip);
        cstmt3.setString(5,address);
        cstmt3.executeUpdate();
      
    }
    catch (SQLException e) {
        //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("ADDRESS NOT INSERTED");
    }
    
       //  After Inserting into database print values into output console   
       System.out.println("First Name: "+fname);
       System.out.println("Last Name: "+lname);
       System.out.println("SSN: "+ssn);
       System.out.println("Sex: "+sex);
       System.out.println("Date Of birth: "+date);
       System.out.println("Address Line: "+address);
       System.out.println("State: "+state);
       System.out.println("City: "+city);
       System.out.println("zip: "+zip);   
    
        
    }                                        

/**************************************************************************
 * UPDATE all values entered by user into database by calling stored procedure.* 
 * In stored procedure, the query executed to update values into tables. 
 **************************************************************************/    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        //UPDATAE button when clicked then handling code here:
        //Get all values from the design interface
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        String mail =  jTextField5.getText();
        String address = jTextField7.getText();  
        String state = jTextField9.getText();
        String city = jTextField6.getText(); 
        jLabel14.setText("");
        int ssn = Integer.parseInt(jTextField4.getText());
        String num = jTextField10.getText();
        int zip = Integer.parseInt(jTextField8.getText());
        String sex=null;
        int d=0,m=0,y=0;
        if(jRadioButton1.isSelected())
        {
            sex = "M";
        }
        else if(jRadioButton2.isSelected())
        {
            sex = "F";
        }
        
        //Get date values from ComboBox
        Object selectedItem = jComboBox3.getSelectedItem();
        if (selectedItem != null)
        {
             String mm = selectedItem.toString();
             m = Integer.parseInt(mm);
        }
        Object selectedItem2 = jComboBox1.getSelectedItem();
        if (selectedItem2 != null)
        {
             String dd = selectedItem2.toString();
             d = Integer.parseInt(dd);
        }
        Object selectedItem3 = jComboBox2.getSelectedItem();
        if (selectedItem3 != null)
        {
             String yy = selectedItem3.toString();
             y = Integer.parseInt(yy);
        }  
        
        //interface CallableStatement declared to execute SQL stored procedures
        CallableStatement cstmt;
        
        //To UPDATE values in the table call procedure where all values are passed as parametes to execute the query. 
        try {
        String SQL = "{call UPDATE_PERSON (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
        cstmt = con.prepareCall (SQL);
        // Set a parameter by index
        cstmt.setString(2,fname);
        cstmt.setString(3,lname);
        cstmt.setInt(1,ssn);
        cstmt.setString(4,sex);
        String date = y+"-"+m+"-"+d;
        cstmt.setString(5,date);
        cstmt.setString(6,mail);
        cstmt.setString(7,address);
        cstmt.setString(8,city);
        cstmt.setString(9,state);
        cstmt.setInt(10,zip);
        cstmt.setString(11,num);
        cstmt.executeUpdate();
    }
    catch (SQLException e) {
        //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("PERSON NOT UPDATED");
    }
      
    }                                        

 /**************************************************************************
 * DELETE all values in the row selected by user into database by calling stored procedure.* 
 * In stored procedure, the query executed to delete values into tables. 
 **************************************************************************/ 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        //DELETE button when clicked then handling code here:
        
        //Row is selected in the table which user want to delete
        //Get the row value of the table 
        int row = jTable2.getSelectedRow();
        
        //Get SSN value of that row
        int s = Integer.parseInt(jTable2.getModel().getValueAt(row, 0).toString());
       
        //interface CallableStatement declared to execute SQL stored procedures
        CallableStatement stmt;
        
        //SSN value is passed while calling a stored procedure to excute delete query. 
        try {
        String SQL = "{call DELETE_TUPLE (?)}";
        stmt = con.prepareCall (SQL);
        // Set a parameter by index
        stmt.setInt(1,s);
        stmt.executeUpdate();
    }
    catch (SQLException e) {
       //Handle errors for java sql
        e.printStackTrace();
        jLabel14.setText("NOT DELETED");
    }
        
    }                                        

/**************************************************************************
 * SEARCH all records which matched with values entered by user into database by calling stored procedure.* 
 * In stored procedure, the query executed to search all values from tables. 
 **************************************************************************/     
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // SEARCH button when clicked then handling code here:
        
        //The DefaultTableModel can be acessed through the getModel method.
        DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        //Get all values from the design interface
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        String mail =  jTextField5.getText();
        String address = jTextField7.getText();  
        String state = jTextField9.getText();
        String city = jTextField6.getText();  
        String ssn = jTextField4.getText();
        String num = jTextField10.getText();
        String zip = jTextField8.getText();
        jLabel14.setText("");
        String mon= jComboBox3.getSelectedItem().toString();
        String day1=jComboBox1.getSelectedItem().toString();
        String year1=jComboBox2.getSelectedItem().toString();
            
        String date = year1+"-"+mon+"-"+day1;
        CallableStatement st1;
        String sex=null;
        if(jRadioButton1.isSelected())
        {
            sex = "M";
        }
        else if(jRadioButton2.isSelected())
        {
            sex = "F";
        }
          
        String fname1= "";
        String lname1= "";
        String phone1 = "";
        String ssn2;
        String date1 = "";
        String sex1 = "";
        String email1 = "";
        String address1="";
        String city1 = "";
        String state1 = "";
        String zip1 = "";
        model.setRowCount(0);
        
        //SEARCH procedure is called by passing all values got from the design interface
        try {
            st1 = con.prepareCall("{call SEARCH_CONTACT(?,?,?,?,?,?,?,?,?,?)}");
            // Set a parameter by index
            st1.setString(1,ssn);
            st1.setString(2,fname);
            st1.setString(3,lname);
            st1.setString(4,num);
            st1.setString(5,sex);   
            st1.setString(6,address);
            st1.setString(7,city);
            st1.setString(8,state);
            st1.setString(9,mail);
            st1.setString(10,zip);
            //st1.setString(11,date);
 
            // Get the result set
            ResultSet rs=st1.executeQuery();
            
            // Position the cursor 
            while(rs.next())
            {
                // process result set
                // Retrieve current result set value
                fname1 = rs.getString("FIRST_NAME");
                lname1 = rs.getString("LAST_NAME");
                phone1 = rs.getString("PHONE");
                ssn2 = rs.getString("SSN"); 
                sex1 = rs.getString("SEX");
                date1= rs.getString("DOB");
                address1=rs.getString("ADDRESS_LINE");
                city1= rs.getString("CITY");
                state1= rs.getString("STATE");
                zip1= rs.getString("ZIP");
                email1=rs.getString("EMAIL");
                
            //set updated values in the design table  
            model.addRow(new Object[]{ssn2, fname1, lname1, date1, sex1, address1, city1, state1, zip1, email1});
            
            }

        } catch (SQLException ex) {
          //Handle errors for java sql
          ex.printStackTrace();
        }


    }                                        

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        // TODO add your handling code here:
        try{
            //Register java sql driver
            Class.forName("java.sql.Driver");
            //Open a connection
            con = DriverManager.getConnection("jdbc:mysql://localHost/contactmanager","root","Sharda@1668");
            jLabel14.setText("Ready");
        }
        catch(Exception e){
            jLabel14.setText("NOT Ready");
        }
        
      
    }                                    

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        
    }                                          

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
          
    }                                          

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         
    }                                          

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

/**************************************************************************
 * RETRIEVE all values from tables in the database by calling stored procedure.* 
 * In stored procedure, the select query executed to get all values from tables. 
 **************************************************************************/     
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // RETRIEVE button when clicked then handling code here:
        
        String fname;
        String lname;
        String phone;
        int ssn=0;
        String date;
        String sex;
        String email;
        String address;
        String city;
        String state;
        int zip;
        String a;
        jLabel14.setText("");
        
        //The DefaultTableModel can be acessed through the getModel method.
        DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        //interface CallableStatement declared to execute SQL stored procedures
        CallableStatement st;
        
        //GETALLCONTACTS procedure is called to retrieve all rows from tables in the database 
        //Set those values in a design table 
        try {
            st = con.prepareCall("{call GETALLCONTACTS()}");
            
            // Get the result set
            ResultSet rs=st.executeQuery();
            
            // Position the cursor
            while(rs.next())
            {
                // process result set
                // Retrieve current result set value
                fname = rs.getString("FIRST_NAME");
                lname = rs.getString("LAST_NAME");
                phone = rs.getString("PHONE");
                ssn = rs.getInt("ssn");
                sex = rs.getString("SEX");
                date = rs.getString("DOB");
                address = rs.getString("ADDRESS_LINE");
                city = rs.getString("CITY");
                state = rs.getString("STATE");
                zip = rs.getInt("ZIP");
                email = rs.getString("EMAIL");
                
            //set retrived values in the design table 
            model.addRow(new Object[]{ssn,fname, lname, date, sex, address, state, city, zip, email, phone});
            }

        } catch (SQLException e) {
           e.printStackTrace();
        }
    
    }                                        

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // when mouse clicked on a row of the table then handling code here:
        int row = jTable2.getSelectedRow();
        //Get all values of a clicked row and set them in the text field of design interface
        jTextField4.setText(jTable2.getModel().getValueAt(row,0).toString());        
        jTextField1.setText(jTable2.getModel().getValueAt(row,1).toString());
        jTextField2.setText(jTable2.getModel().getValueAt(row,2).toString());
        jTextField5.setText(jTable2.getModel().getValueAt(row,9).toString());
        jTextField7.setText(jTable2.getModel().getValueAt(row,5).toString());
        jTextField9.setText(jTable2.getModel().getValueAt(row,6).toString());
        jTextField6.setText(jTable2.getModel().getValueAt(row,7).toString());
        jTextField8.setText(jTable2.getModel().getValueAt(row,8).toString());
        jTextField10.setText(jTable2.getModel().getValueAt(row,10).toString());
        String date=jTable2.getModel().getValueAt(row,3).toString();
        String[] words=date.split("-");
        for(String w:words){  
            System.out.println(w);  
        }  
        jComboBox2.setSelectedItem(words[0]);
        jComboBox3.setSelectedItem(words[1]);
        jComboBox1.setSelectedItem(words[2]);
        
        String sex=jTable2.getModel().getValueAt(row,4).toString();
        
        if(sex == "M")
        {
            jRadioButton1.setSelected(true);
        }
        else if(sex == "F")
        {
            jRadioButton2.setSelected(true);
        }
    }                                    
/**************************************************************************
 * CLEAR all values entered by user from design interface.
 **************************************************************************/ 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // CLEAR button when clicked the handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jLabel14.setText("");
    }                                        

/**************************************************************************
 * Validate phone number jTextField so that user only enter digits as the input.  
 **************************************************************************/
    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
       
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9 || (key==evt.VK_BACK_SPACE) ))
        {
           jTextField10.setEditable(true);
        }
        else
        {
           getToolkit().beep();
           jTextField10.setEditable(false);
           jTextField10.setBackground(Color.red); 
        }
        
    }                                       
/**************************************************************************
 * Validate ZIP CODE jTextField so that user only enter digits as the input.  
 **************************************************************************/
    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9 || (key==evt.VK_BACK_SPACE) ))
        {
           jTextField8.setEditable(true);
        }
        else
        {
           getToolkit().beep();
           jTextField8.setEditable(false);
           jTextField8.setBackground(Color.red); 
        }
    }                                      
/**************************************************************************
 * Validate SSN jTextField so that user only enter digits as the input.  
 **************************************************************************/
    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9 || (key==evt.VK_BACK_SPACE) ))
        {
           jTextField4.setEditable(true);
        }
        else
        {
           getToolkit().beep();
           jTextField4.setEditable(false);
           jTextField4.setBackground(Color.red); 
        }
    }                                      
/**************************************************************************
 * Validate phone number jTextField so that user only enter 10 digits max.  
 **************************************************************************/
    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        boolean max = jTextField10.getText().length() >=  10 ;
        if ( max ){
            evt.consume();
        }    
    }                                     
/**************************************************************************
 * Validate SSN jTextField so that user only enter 9 digits max.  
 **************************************************************************/
    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        boolean max = jTextField4.getText().length() >=  9 ;
        if ( max ){
            evt.consume();
        }  
    }                                    
/**************************************************************************
 * Validate ZIP CODE jTextField so that user only enter 5 digits max.  
 **************************************************************************/
    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        boolean max = jTextField8.getText().length() >=  5 ;
        if ( max ){
            evt.consume();
        }
        
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                   
    static Connection con = null;
  
}
