USE contactmanager;

CREATE TABLE PERSON (SSN INT(9), FIRST_NAME VARCHAR(15) NOT NULL, LAST_NAME VARCHAR(15), SEX CHAR(1), DOB DATE, PRIMARY KEY(SSN));

CREATE TABLE EMAIL(EMAIL VARCHAR(30),PERSON_ID INT(9), FOREIGN KEY(PERSON_ID) REFERENCES PERSON(SSN) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE CONTACT(PHONE VARCHAR(10), PERSON_ID INT(9), FOREIGN KEY(PERSON_ID) REFERENCES PERSON(SSN) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ADDRESS(PERSON_ID INT, CITY VARCHAR(15),STATE VARCHAR(15), ZIP INT(10),ADDRESS_LINE VARCHAR(30), PRIMARY KEY(ID), FOREIGN KEY(PERSON_ID) REFERENCES PERSON(SSN)  ON DELETE CASCADE ON UPDATE CASCADE);

ALTER TABLE PERSON ADD constraint VALID CHECK (SSN < 10);
ALTER TABLE CONTACT ADD constraint NUMVALID CHECK (PHONE < 11);
ALTER TABLE ADDRESS ADD constraint ZIPVALID CHECK (ZIP < 6);
