CREATE DEFINER=`root`@`localhost` PROCEDURE `GETALLCONTACTS`()
BEGIN
select a.FIRST_NAME, a.LAST_NAME, c.PHONE, a.SSN ,a.SEX, a.DOB , d.ADDRESS_LINE, d.CITY, d.STATE, d.ZIP, b.EMAIL  
FROM PERSON a 
INNER JOIN CONTACT c ON a.SSN = c.PERSON_ID
INNER JOIN EMAIL b ON a.SSN = b.PERSON_ID
INNER JOIN ADDRESS d ON a.SSN = d.PERSON_ID;
END