CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_ADDRESS`(IN PERSON_ID INT(9), IN CITY VARCHAR(15), IN STATE VARCHAR(15), IN ZIP INT(10), IN LINE VARCHAR(30))
BEGIN
	INSERT INTO ADDRESS VALUES (PERSON_ID, CITY, STATE, ZIP, LINE);
END