CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_PERSON`(IN SSN int(9), IN FNAME varchar(15), IN LNAME varchar(15), IN SEX char(1), IN BDATE DATE)
BEGIN
	INSERT INTO PERSON VALUES (SSN, FNAME, LNAME, SEX, BDATE);
END