CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_PERSON`(IN PK int(9), IN FNAME varchar(15), IN LNAME varchar(15), IN S char(1), IN BDATE DATE, IN MAIL VARCHAR(20),IN AD VARCHAR(30), IN C VARCHAR(10), IN ST VARCHAR(10), IN Z INT(10), IN P VARCHAR(10))
BEGIN
   UPDATE PERSON SET FIRST_NAME = FNAME, LAST_NAME=LNAME, DOB=BDATE WHERE SSN=PK;
   UPDATE EMAIL SET EMAIL=MAIL WHERE PERSON_ID=PK;
   UPDATE CONTACT SET PHONE=P WHERE PERSON_ID=PK;
   UPDATE ADDRESS SET ADDRESS_LINE=AD, CITY=C, STATE=ST, ZIP=Z WHERE PERSON_ID=PK;
END